### ISSUE TITLE
need auto-start option and memory function and language

### ISSUE THREAD

**Issue by yhdxczz** [xifangczy/ScrollVolume#1]
The auto-start option，and the taskbar mouse wheel adjustment volume memory function still need to be manually selected after operation
Whether the software can add language selection, it would be nice to have Chinese
![PixPin_2024-07-23_04-41-39](https://github.com/user-attachments/assets/4ad185df-ec06-4ccc-99bf-3a49e9a51654)

**Comment by xifangczy** [comment]
记忆功能... 行吧

多语言... 总共就三句 就没必要了吧😂

**Comment by xifangczy** [comment]
记忆配置已经添加。

**Comment by yhdxczz** [comment]
![PixPin_2024-07-23_06-47-20](https://github.com/user-attachments/assets/f4ddd892-15d7-43ae-b6c3-db6cbfe4551f)
这样就能开机自启，并且默认任务栏鼠标滚轮控制音量了吗？

**Comment by xifangczy** [comment]
> 这样就能开机自启，并且默认任务栏鼠标滚轮控制音量了吗？

是的

**Comment by yhdxczz** [comment]
好的，谢谢
