### ISSUE TITLE
Emulate the action left mouse button click when we activate unroll mouse wheel to avoid hand finger joint pain

### ISSUE THREAD

**Issue by trimechee** [xifangczy/ScrollVolume#2]
Hi, thank you so much for this wonderful extraordinary great and very useful! software technological jewel ! 💯 🥇 

I have a suggestion please, sometimes we do a lot of research and the articulation of our finger gets tired painful to click on many links with the left button of the mouse, in addition the mouse may not work properly (because of dust, dirt, entry-level mouse not performing well ....) and so the left button click may not work very well and we have to click several times for the click to work properly so my suggestion please is to emulate the action left mouse button when we activate mouse wheel, so it will be more comfortable for the articulation of our fingers and it allows to extend the global duration of functioning of the mouse, thank you so much !

**Comment by trimechee** [comment]
i finf this chinese software, but i don't know if it is open source : 

https://getquicker.net/

**Comment by trimechee** [comment]
Mr @xifangczy , grat news, Mr Jersou the developer of Mouss-actions make this feat  and  respond me :  

"  You can achieve this with xdotool and this config:
(screenshot) 
→ on mouse wheel down "release", do click with left button."

**Comment by xifangczy** [comment]
你的要求和本项目无关。你的要求有很多软件可以实现。

Your request is unrelated to this project. Your request can be fulfilled by many software programs.

**Comment by trimechee** [comment]
We undertand, thank you :) i request this because other programs may have zombie prcessus, be too heavy...but no problem , There are vertical mouse that are more comfortable than classic mouse....
