### ISSUE TITLE
mouse-actions open source program, and move mouse open source program 

### ISSUE THREAD

**Issue by trimechee** [xifangczy/ScrollVolume#3]
Hi, i find this open source software, maybe it can help our beloved ScrollVolume to realize our ultimate dream to emulate the action left mouse button click when we activate unroll mouse wheel to avoid hand finger joint pain please :

https://github.com/jersou/mouse-actions

https://github.com/xifangczy/ScrollVolume/issues/2

update : 

and also : 

https://github.com/sw3103/movemouse

**Comment by trimechee** [comment]
and also :

https://github.com/sw3103/movemouse

**Comment by xifangczy** [comment]
#2 Already answered
